require: rubocop-rails

inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - spec/**/*
Documentation:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
